---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: gg2-os
# description will be included in the image's metadata
description: Customized image to include Firefox and 1Password in the base.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-nvidia-open
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /
  - from-file: common/fonts.yml
  - from-file: common/packages.yml
  - from-file: common/flatpaks.yml
  - from-file: common/bling.yml
  - type: signing
